export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const MOUSE_CHANGE = 'header/MOUSE_CHANGE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'
